### ISSUE TITLE
Train test split

### ISSUE THREAD

**Issue by waormd** [fracpete/python-weka-wrapper3#10]
Hi,

I have predetermined train and test files but can't figure out how to use evaluate my test data after a classifier has been built. 

I do not want to use cross validation or anything, purely train a classifier with my existing training file then evaluate it against the test file. 

In the Evaluation class I have not been able to achieve this without reshuffling my train and test files which I do not want to do. 

Any recommendations would be helpful, thanks a lot!

**Comment by fracpete** [comment]
Just use the test_model method:
http://fracpete.github.io/python-weka-wrapper3/weka.html#weka.classifiers.Evaluation.test_model

For questions, please use the mailing list:
https://groups.google.com/forum/m/#!forum/python-weka-wrapper
