### ISSUE TITLE
Unable to use python-weka-wrapper on macos

### ISSUE THREAD

**Issue by addyag93** [fracpete/python-weka-wrapper3#14]
Following is the error I am getting
I am unsure of what package file to use .
Link given to variable "packages" is from Weka application wekafiles
I am getting this error while running it in PyCharm

jvm.start(system_cp=True, packages='/Users/addy93/wekafiles/packages')
DEBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Adding system classpath
DEBUG:weka.core.jvm:Classpath=['/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/javabridge/jars/rhino-1.7R4.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/javabridge/jars/runnablequeue.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/javabridge/jars/cpython.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Applications/weka-3-8-0/weka.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Applications/weka-3-8-0/weka.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Applications/weka-3-8-0/weka.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Applications/weka-3-8-0/weka.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Applications/weka-3-8-0/weka.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar']
DEBUG:weka.core.jvm:MaxHeapSize=default
DEBUG:weka.core.jvm:Using alternative Weka home directory: /Users/addy93/wekafiles/packages
Failed to get class Lweka/core/Environment;
Exception in thread "Thread-21" java.lang.NoClassDefFoundError: Lweka/core/Environment;
Caused by: java.lang.ClassNotFoundException: weka.core.Environment
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/core/jvm.py", line 114, in start
    env = Environment.system_wide()
  File "/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/core/classes.py", line 729, in system_wide
    "Lweka/core/Environment;", "getSystemWide", "()Lweka/core/Environment;"))
  File "/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/javabridge/jutil.py", line 934, in static_call
    fn = make_static_call(class_name, method_name, sig)
  File "/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/javabridge/jutil.py", line 908, in make_static_call
    raise JavaException(jexception)
javabridge.jutil.JavaException: Lweka/core/Environment;

**Comment by fracpete** [comment]
There are a number of problems:

* pwww3 is designed for Weka 3.9.x and cannot be used with 3.8.x
* the alternative packages directory that you specified is the default one, just use `packages=True`
* don't turn on `system_cp`, as you seem to have lots of duplicate jars in there and also Weka 3.8.x

In other words, what happens when you use the following instead to start up the JVM:
```
jvm.start(packages=True)
```

**Comment by addyag93** [comment]
This is the error I am getting:
Also: I m not getting any **weka.jar** while installing python-weka-wrapper3

DEBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Classpath=['/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/javabridge/jars/rhino-1.7R4.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/javabridge/jars/runnablequeue.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/javabridge/jars/cpython.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar']
DEBUG:weka.core.jvm:MaxHeapSize=default
DEBUG:weka.core.jvm:Package support enabled
DEBUG:javabridge.jutil:Creating JVM object
DEBUG:javabridge.jutil:Launching VM in non-python thread
DEBUG:javabridge.jutil:Attaching to VM in monitor thread
DEBUG:javabridge.jutil:Signalling caller
Failed to get class Lweka/core/WekaPackageManager;
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: Lweka/core/WekaPackageManager;
Caused by: java.lang.ClassNotFoundException: weka.core.WekaPackageManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Traceback (most recent call last):
  File "/Users/addy93/PycharmProjects/Test/venv/tf-idf", line 84, in <module>
    jvm.start(packages=True)
  File "/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/core/jvm.py", line 122, in start
    False)
  File "/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/javabridge/jutil.py", line 934, in static_call
    fn = make_static_call(class_name, method_name, sig)
  File "/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/javabridge/jutil.py", line 908, in make_static_call
    raise JavaException(jexception)
javabridge.jutil.JavaException: Lweka/core/WekaPackageManager;

**Comment by fracpete** [comment]
The `weka.jar` gets downloaded from github during the installation.
How are you installing pww3? Can you please post all your steps to set up your virtual environment?

**Comment by addyag93** [comment]
I am installing python-weka-wrapper3 using Pycharm Python Interpreter.
![screenshot 2018-08-30 09 48 53](https://user-images.githubusercontent.com/14900407/44829367-10848100-ac3a-11e8-8fcc-421ee2cca96c.png)

**Comment by fracpete** [comment]
Never tested that before. I tend to install from a terminal and then set up PyCharm afterwards.
Are you behind a proxy? Did you see any errors during the installation (console output)?

**Comment by addyag93** [comment]
No, I haven't seen any problem on console output while installing it. it installed fine.  Could you please help me with terminal installation steps.

**Comment by fracpete** [comment]
Here is what I do under Linux (you may have to install `virtualenv` on your system first):
```
virtualenv -p /usr/bin/python3.5 venv
./venv/bin/pip install javabridge==1.0.14
./venv/bin/pip install python-weka-wrapper3
```
Notes:
* You may have to adjust the location of your Python 3 interpreter.
* The above installs the virtual environment in the current directory into `venv`. I've only ever tested with version 1.0.14 of javabridge under Python 3.5, hence the condition.

**Comment by addyag93** [comment]
Hey, 
 I set my environment to python 3.6 and installed pwww3 using the terminal. It installed fine. But the problem still exists.
I tried installing using **conda** but it throws package not found error. 
(See if I am doing anything wrong)
EBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Classpath=['/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/javabridge/jars/rhino-1.7R4.jar', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/javabridge/jars/runnablequeue.jar', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/javabridge/jars/cpython.jar', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar']
DEBUG:weka.core.jvm:MaxHeapSize=default
DEBUG:weka.core.jvm:Package support enabled
DEBUG:javabridge.jutil:Creating JVM object
DEBUG:javabridge.jutil:Launching VM in non-python thread
DEBUG:javabridge.jutil:Attaching to VM in monitor thread
DEBUG:javabridge.jutil:Signalling caller
Failed to get class Lweka/core/WekaPackageManager;
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: Lweka/core/WekaPackageManager;
Caused by: java.lang.ClassNotFoundException: weka.core.WekaPackageManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Traceback (most recent call last):
  File "/Users/addy93/PycharmProjects/Test/venv/tf-idf", line 85, in <module>
    jvm.start(packages=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/weka/core/jvm.py", line 122, in start
    False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/javabridge/jutil.py", line 934, in static_call
    fn = make_static_call(class_name, method_name, sig)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/javabridge/jutil.py", line 908, in make_static_call
    raise JavaException(jexception)
javabridge.jutil.JavaException: Lweka/core/WekaPackageManager;

Process finished with exit code 130 (interrupted by signal 2: SIGINT)

**Comment by fracpete** [comment]
You didn't my question regarding proxy... Other people had problems with Anaconda on OSX as well.
Open an interactive Python shell from your virtual environment and run the following code (the code that the `setup.py` script uses):

```python
from urllib.request import urlopen, URLError, HTTPError

def download_file(url, outfile):
    try:
        # Open the url
        f = urlopen(url)
        print("Downloading '" + url + "' to '" + outfile + "'")
        # Open our local file for writing
        with open(outfile, "wb") as local_file:
            local_file.write(f.read())
    # handle errors
    except HTTPError as e:
        print("HTTP Error: " + str(e.code) + " " + url)
        return False
    except URLError as e:
        print("URL Error: " + str(e.reason) + " " + url)
        return False
    return True

url = "https://github.com/fracpete/python-weka-wrapper3/blob/64a4175eaa8f6b7eeee82c0ab356d4df11688a11/python/weka/lib/weka.jar?raw=true"
outfile = path.join(".", "weka.jar")
if not download_file(url, outfile):
    print("Failed to download Weka jar '" + url + "' to '" + outfile + "'!")
else:
    print("Download of Weka jar successful!")
```

**Comment by addyag93** [comment]
I just downloaded the provided GitHub URL and paste it in the package folder. In my case, it worked.

Thanks man.

**Comment by fracpete** [comment]
As an alternative, clone the repo and install pww3 via the setup.py script. The you'll have the weka.jar as well.

**Comment by fracpete** [comment]
Release 0.1.5 now includes the weka.jar and no longer downloads it during installation. That should hopefully solve this issue.
