### ISSUE TITLE
Making predictions without target variable.

### ISSUE THREAD

**Issue by SethuramanJ** [fracpete/python-weka-wrapper3#2]
Hello, Please refer to this post in stackoverflow
The question: is there a way to insert '?' character for unknown values while creating instances just before making predictions? other than reading them from .csv or .arff files

Thank you.

**Comment by fracpete** [comment]
You didn't provide a link to the stackoverflow question, so I'll just answer it here. Why don't you just create your data on the fly? Here is an example for dealing with the Instances data structure:
https://github.com/fracpete/python-weka-wrapper3-examples/blob/master/src/wekaexamples/core/dataset.py

**Comment by SethuramanJ** [comment]
Hello,
I missed to paste the link sorry. However you have replied in [the post](http://stackoverflow.com/questions/38919132/regression-test-data-for-prediction-requires-class-value-in-weka/) with an answer. 
I am not familiar with working in java. The link that you have provided for Add filter is for implementation in Java. I am using this example for creating attributes and instances, but for a numeric attribute, how to add '?' on the go? Can you please tell me how to implement this in python? cite some example? 
Thanks!
