### ISSUE TITLE
probabilityCalibrationTrees 

### ISSUE THREAD

**Issue by farzadhallaji** [fracpete/python-weka-wrapper3#22]
how I can use [probabilityCalibrationTrees](http://weka.sourceforge.net/doc.packages/probabilityCalibrationTrees) class from weka?
when will it be supported?

**Comment by fracpete** [comment]
For questions, please use the mailing list:
https://groups.google.com/forum/#!forum/python-weka-wrapper

Your link was broken, I presume you're referring to this Weka package:
http://weka.sourceforge.net/packageMetaData/probabilityCalibrationTrees/index.html

Install the package and start the JVM with package support:
http://fracpete.github.io/python-weka-wrapper3/api.html#java-virtual-machine
http://fracpete.github.io/python-weka-wrapper3/api.html#packages
