### ISSUE TITLE
need help with java heap space 

### ISSUE THREAD

**Issue by pigeon2049** [fracpete/python-weka-wrapper3#23]
<pre>
def main():
    loader = Loader(classname="weka.core.converters.ArffLoader")
    saved_file = "..\\resource\\saved2.arff"
    data = loader.load_file(saved_file)
    data.class_is_first()
    train, test = data.train_test_split(66.0, Random(1))
    classifier = Classifier(classname="weka.classifiers.bayes.BayesNet",
                            options=["-D", "-Q", "weka.classifiers.bayes.net.search.local.K2",
                                     "-E", "weka.classifiers.bayes.net.estimate.SimpleEstimator"])
    classifier.build_classifier(train)
    evaluation = Evaluation(train)
    evaluation.test_model(classifier, test)
    print(evaluation.summary())
    print("pctCorrect: " + str(evaluation.percent_correct))
    print("incorrect: " + str(evaluation.incorrect))
    print(evaluation.matrix())

if __name__ == "__main__":
    try:
        os.environ["_JAVA_OPTIONS"] = "-Xms128m -Xmx24576m -Dfile.encoding=UTF-8"
        jvm.start(packages=True,max_heap_size="24576m")
        main()
    except Exception as e:
        print(e.__str__())
    finally:
        jvm.stop()
</pre>
<pre>
C:\Users\zgl\AppData\Local\Programs\Python\Python37\python.exe C:/Users/zgl/PycharmProjects/weka-program-master/code/WekaTextCategorization.py
DEBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Classpath=['C:\\Users\\zgl\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\javabridge\\jars\\rhino-1.7R4.jar', 'C:\\Users\\zgl\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\javabridge\\jars\\runnablequeue.jar', 'C:\\Users\\zgl\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\javabridge\\jars\\cpython.jar', 'C:\\Users\\zgl\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\weka\\lib\\python-weka-wrapper.jar', 'C:\\Users\\zgl\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\weka\\lib\\weka.jar']
DEBUG:weka.core.jvm:MaxHeapSize=24576m
DEBUG:weka.core.jvm:Package support enabled
java.lang.OutOfMemoryError: Java heap space
	weka.classifiers.bayes.net.ParentSet.<init>(ParentSet.java:135)
	weka.classifiers.bayes.BayesNet.initStructure(BayesNet.java:325)
	weka.classifiers.bayes.BayesNet.buildClassifier(BayesNet.java:224)

	at weka.classifiers.bayes.net.ParentSet.<init>(ParentSet.java:135)
	at weka.classifiers.bayes.BayesNet.initStructure(BayesNet.java:325)
	at weka.classifiers.bayes.BayesNet.buildClassifier(BayesNet.java:224)
Java heap space
Picked up _JAVA_OPTIONS: -Xms128m -Xmx24576m -Dfile.encoding=UTF-8
Exception in thread "Thread-0" 
Process finished with exit code 0
</pre> 
I changed java heap space with max_heap_size="24576m" and it seems  worked,but after 8-9 hours running it still warning Java heap space Exception.
Maybe it's a problem of Memory Leak.
Or i wrote wrong code?
Can you help me?

**Comment by fracpete** [comment]
Please use the project's mailing list for questions.

Don't use "-Xms". You can specify the maximum heap size when starting up the JVM:
http://fracpete.github.io/python-weka-wrapper3/api.html#java-virtual-machine

It may be a problem of your combination of dataset/classifier. Try another classifier, like `weka.classifiers.rules.ZeroR` (as baseline) and then something more sophisticated like `weka.classifiers.trees.J48`.

**Comment by pigeon2049** [comment]
Thank you
