### ISSUE TITLE
Common issue found while pip3 installing python-weka-wrapper3

### ISSUE THREAD

**Issue by SachitNayak** [fracpete/python-weka-wrapper3#24]
```
Collecting python-weka-wrapper3
  Downloading https://files.pythonhosted.org/packages/48/3a/0f345b19774b5b6c53e9456c2985d79ff09b610bbf29d95403004734a45b/python-weka-wrapper3-0.1.7.tar.gz (10.1MB)
     |████████████████████████████████| 10.1MB 22.0MB/s 
Collecting javabridge>=1.0.14 (from python-weka-wrapper3)
  Downloading https://files.pythonhosted.org/packages/a6/a0/c59bccabed99b1d4ac68166c59c679b375bfca75b78688b52c541b711578/javabridge-1.0.18.tar.gz (1.3MB)
     |████████████████████████████████| 1.3MB 22.1MB/s 
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_s3z91hy/javabridge/
```
Many of my friends and I are facing this issue while installing python-weka-wrapper3 for a project

**Comment by fracpete** [comment]
I presume that you are running Ubuntu or a derivative...
Do you have all the required packages installed?
http://fracpete.github.io/python-weka-wrapper3/install.html#ubuntu

**Comment by SachitNayak** [comment]
yup! double checked it still fails.

I think the issue seems to lie with javabridge installation and not with this package. I'll try rectifying javabridge first and then re-open this thread if the issue still persists.

Thanks :)

**Comment by Abo7atm** [comment]
I've had the same problem, but on macOS. Setting JAVA_HOME variable to your Java home and exporting it before running `pip install javabridge` fixed it for me.

**Comment by SachitNayak** [comment]
I actually had set the JAVA_HOME correctly. The issue was that javac (JDK) was not installed on my machine. Even though the jdk folders might exist in the machine it doesn't necessarily mean that JVM is installed on the machine. I had to apt install openjdk inorder to ensure JDK was properly installed on the machine and then javabridge installed smoothly. Obviously python-weka-wrapper3 then installed smoothly. Please note I could smoothly install the wrapper and all dependencies using pip3 and apt install itself. Didn't have to install anything from source.

**Comment by fracpete** [comment]
Installing a JDK was one of the prerequisites (Java header files are required for compiling javabridge).

**Comment by SachitNayak** [comment]
> Installing a JDK was one of the prerequisites (Java header files are required for compiling javabridge).

Yes I'm aware; it's just that **after looking at directory listings like _/usr/lib/jvm/java-11-openjdk-amd64/bin/_** I **presumed that JDK was already installed on the Google Colab instance**. **However** I realized **that is not the case** please see [link](https://stackoverflow.com/questions/55718535/cannot-install-python-weka-wrapper-javabridge-on-google-colab/56902590#56902590)

and then I installed openjdk and everthing worked smoothly after that. Frankly speaking, it was silly of me, not to have double checked installation by running javac on a sample java program.

Aside:
Oh one other thing I noticed in the pre-requisites in the installation guidelines [here](https://fracpete.github.io/python-weka-wrapper3/install.html)  is that it states to  install python-pygraphviz as a prerequisite. I guess it should be python**3**-pygraphviz for python-weka-wrapper3.

Thank you so much

**Comment by fracpete** [comment]
I added a Q/A to the troubleshooting page regarding the failure to compile javabridge. It stresses the point that a JDK has to be installed (can be tested via `javac` command) and that the `JAVA_HOME` env variable maybe necessary to set.
Thanks for reporting the typo in the package, just fixed it.

**Comment by SachitNayak** [comment]
I'm glad that I could humbly contribute in some way at least that might help other people. Thank you so much. I hope people will be able to install java bridge without any hassles now. python-weka-wrapper3 is a fantastic package!

Aside: I notice that under the Debian installation instructions, the aforementioned typo is still present. I figured I might bring it to your notice.

**Comment by fracpete** [comment]
Thanks for picking that up! :-) Just pushed out an update. The documentation is based on the Python 2.7 version, so there were bound to be some typos in there... Glad you like the wrapper!
