### ISSUE TITLE
How to set the weight?

### ISSUE THREAD

**Issue by huyenpham2995** [fracpete/python-weka-wrapper3#25]
I'm trying to set the weight for an instance using
`inst.weight(0.1)` but I receive the following error

<img width="462" alt="Screen Shot 2019-10-25 at 1 25 34 PM" src="https://user-images.githubusercontent.com/38078261/67602196-f43f7f80-f72a-11e9-9180-85db2852d743.png">

I can print the weight with `inst.weight`

Could you please help me with that?

**Comment by fracpete** [comment]
On October 26, 2019 9:27:09 AM GMT+13:00, Huyen Pham <notifications@github.com> wrote:
>I'm trying to set the weight for an instance using
>`inst.weight(0.1)` but I receive the following error
>
><img width="462" alt="Screen Shot 2019-10-25 at 1 25 34 PM"
>src="https://user-images.githubusercontent.com/38078261/67602196-f43f7f80-f72a-11e9-9180-85db2852d743.png">
>
>I can print the weight with `inst.weight`
>
>Could you please help me with that?

"weight" is a property, not a method:
x.weight = 0.1
y = x.weight

Cheers, Peter
--
Peter Reutemann
Dept. of Computer Science
University of Waikato, NZ
+64 (7) 858-5174
http://www.cms.waikato.ac.nz/~fracpete/
http://www.data-mining.co.nz/
