### ISSUE TITLE
create_instances_from_matrices: There are no fields in dtype int64 with version 0.1.8

### ISSUE THREAD

**Issue by severus-sn4pe** [fracpete/python-weka-wrapper3#26]
Since updating to version `0.1.8`, the method `create_instances_from_matrices` does not working the same as before with version `0.1.7`. When passing a numpy-array from a pandas Dataframe with only numerical values, I get a `KeyError: 'There are no fields in dtype int64.'` 

Stack trace
```
/opt/conda/lib/python3.7/site-packages/weka/core/dataset.py in create_instances_from_matrices(x, y, name)
   1589     type_x = []
   1590     for i in range(len(x[0])):
-> 1591         if np.issubdtype(x.dtype[i], np.number):
   1592             type_x.append("N")  # number
   1593             atts.append(Attribute.create_numeric("x" + str(i+1)))

KeyError: 'There are no fields in dtype float64.'
```

We pass a numpy array like this:
```
import numpy as np
import pandas as pd
import weka.core.dataset as ds

my_dataframe = pd.DataFrame(...)
weka_data = ds.create_instances_from_matrices(np.array(my_dataframe))
...
```

this worked flawlessly with the previous version, so using `pip install python-weka-wrapper3==0.1.7` the code above runs fine.

**Comment by fracpete** [comment]
Please try again with 0.1.9 release.

**Comment by severus-sn4pe** [comment]
sure, thanks for the fast response.
can you please add a tag/release so I can get the new version with pip install?

**Comment by fracpete** [comment]
It has already been released on pypi.org:
https://pypi.org/project/python-weka-wrapper3/

**Comment by severus-sn4pe** [comment]
can confirm that it's working again with version`0.1.9`.
thanks for the fast fix 👍

**Comment by fracpete** [comment]
No worries. Thanks for verifying!
