### ISSUE TITLE
Problems deserialising model trained in Fiji

### ISSUE THREAD

**Issue by Gonza10V** [fracpete/python-weka-wrapper3#32]
I had run:
`import os
import tempfile
import traceback
import javabridge
import weka.core.jvm as jvm
#import wekaexamples.helper as helper
from weka.core.converters import Loader
from weka.core.dataset import Instances
from weka.classifiers import Classifier
import weka.core.serialization as serialization
jvm.start()

model, _ = Classifier.deserialize('omm.model')
print(model)`
 
Getting as return, this error:
JavaException: Unable to find class hr.irb.fastRandomForest.FastRandomForest

Im trying to use a model trained using trainable Weka in Fiji in python scripts, how can I do that?

**Comment by fracpete** [comment]
On July 6, 2020 5:28:45 PM GMT+12:00, Gonza10V <notifications@github.com> wrote:
>I had run:
>`import os
>import tempfile
>import traceback
>import javabridge
>import weka.core.jvm as jvm
>#import wekaexamples.helper as helper
>from weka.core.converters import Loader
>from weka.core.dataset import Instances
>from weka.classifiers import Classifier
>import weka.core.serialization as serialization
>jvm.start()
>
>model, _ = Classifier.deserialize('omm.model')
>print(model)`
> 
>Getting as return, this error:
>JavaException: Unable to find class
>hr.irb.fastRandomForest.FastRandomForest
>
>Im trying to use a model trained using trainable Weka in Fiji in python
>scripts, how can I do that? 

You didn't start pww with package support (off by default):

http://fracpete.github.io/python-weka-wrapper3/weka.core.html#weka.core.jvm.start

Cheers, Peter
--
Peter Reutemann
Dept. of Computer Science
University of Waikato, NZ
+64 (7) 858-5174
http://www.cms.waikato.ac.nz/~fracpete/
http://www.data-mining.co.nz/

**Comment by Gonza10V** [comment]
Hi, thanks for your quick response.  Now I start pww with package support:
` jvm.start(packages=True)`
getting:
`DEBUG:weka.core.jvm:Package support enabled`
but it returns the same error:
`JavaException: Unable to find class hr.irb.fastRandomForest.FastRandomForest`

What else can I do to make it work? Have I done something wrong?
Thanks for your help

**Comment by fracpete** [comment]
Did you not install the FastRandomForest package through Weka's package manager? pww comes with its own `weka.jar` and uses the default Weka home directory (on Linux this is `$USER/.wekafiles`) when starting up with package support enabled. The Weka home directory contains the installed packages. If you need to add additional jar files to the class path, you can do that as well using the `class_path` parameter of the [jvm.start](http://fracpete.github.io/python-weka-wrapper3/weka.core.html#weka.core.jvm.start) method.

**Comment by Gonza10V** [comment]
Hi, no I didnt found FastRandomForest package using the Wekas package manager, but I download the Github folder: https://github.com/fracpete/fastrandomforest-weka-package and paste it into wekafiles/packages (the folder where the packages installed with the Weka package manager seems to be stored, I just download a random package and track changes on OSX). It seems to work, no it returns:
`FastRandomForest of 200 trees, each constructed while considering 2 random features.`
`Out of bag error: 0.235%`
But Im a bit confused on how should I use it. 
-I trained a model using trainable Weka in Fiji, for segmentation.
-Save the model and loaded it into python.
And now I want to load .tif files and segment them using the trained model, so I have the following questions:
Can I load a .tif using Weka Loader or should I create a dataset from the np.array extracted from that .tif?
Im aware that the classifier needs a inst.jobject

Is possible to do it using pww or should I run an script in Fiji for this particular use?

**Comment by fracpete** [comment]
That's not how you install an unofficial Weka package. Instead, you download a release zip file (see the *Releases* section on that github project page) and install that zip properly through the Weka package manager - either using Weka's user interface or the appropriate pww API calls. I assumed that you were familiar with the package manager, as your initial post quoted a class from that unofficial package.

If you want to use image segmentation, you will have to go through Fiji, I'm afraid (also, I'm not familiar with Fiji). pww is for Weka and Weka only (as the name suggests). Any other functionality that Fiji offers is not available through the pww Python interfaces.

**Comment by Gonza10V** [comment]
Thanks you very much for your answers, great response time 👍
