### ISSUE TITLE
Syntax Error 

### ISSUE THREAD

**Issue by sakshamnagpal** [fracpete/python-weka-wrapper3#34]
Hi,

I encountered a syntax error while trying to use weka.core.converters Loader. The error is as follows: 

`Traceback (most recent call last):
  File "/Users/username/Predictor/test.py", line 1, in <module>
    from weka.core.converters import Loader
  File "/Users/username/.conda/envs/Predictor/lib/python3.8/site-packages/weka/core/converters.py", line 18, in <module>
    from weka.core.classes import OptionHandler
  File "/Users/username/.conda/envs/Predictor/lib/python3.8/site-packages/weka/core/classes.py", line 2085
    except Exception, e:
                    ^
SyntaxError: invalid syntax`

The system configuration I'm using is as follows: 

1. **Java Version**
java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)

2. **Javabridge Version** - 1.0.19

3. **PWW** - Version for Python 3

4. Operating System - MacOS Catalina

5. **Python** Version - Python 3.8.3

I'm not sure if I'm missing anything but I am unable to continue. Any help would be greatly appreciated. 

Thank you.

**Comment by fracpete** [comment]
Since `except Exception, e` is Python 2 syntax and the `python-weka-wrapper3` code base, which is Python 3, doesn't contain that at all, I can only presume that you installed the `python-weka-wrapper` package instead of `python-weka-wrapper3`. You can check this by running `pip freeze`.

**Comment by sakshamnagpal** [comment]
That resolved my query, thank you so much! 

> Since `except Exception, e` is Python 2 syntax and the `python-weka-wrapper3` code base, which is Python 3, doesn't contain that at all, I can only presume that you installed the `python-weka-wrapper` package instead of `python-weka-wrapper3`. You can check this by running `pip freeze`.
