### ISSUE TITLE
Access protected attribute of Java class

### ISSUE THREAD

**Issue by m-martin-j** [fracpete/python-weka-wrapper3#42]
_Question_

Version:
python = "3.9.*"
python-weka-wrapper3 = "0.2.10"
python-javabridge = "4.0.3"

Hello,

I am attempting to access the attribute `protected Vector<double[][]> matricesDilca` of the Java class [DilcaDistance](https://svn.cms.waikato.ac.nz/svn/weka/trunk/packages/external/DilcaDistance/src/main/java/weka/core/DilcaDistance.java) (external Weka package) from Python.

A Java method `toString` is implemented in said class, accessible via Python method `__str__`. This enables the re-assembly of the attribute-included matrices somewhat awkwardly from a string representation of floating-point data.
Is there another way to more elegantly transfer an actual array along the javabridge? Is it possible to somehow access said attribute `protected Vector<double[][]> matricesDilca` directly from Python and assign its value to a numpy array?

Thank you very much!

**Comment by fracpete** [comment]
0.2.10 is not yet officially released. ;-)

If I remember correctly, only public methods can be accessed via javabridge (just like any other Java library basically).

You would need to subclass the class, make the relevant methods public (and just call the inherited methods). Then you should be able to use the ".jwrapper" property (that any wrapper in pww offers) to obtain a wrapper for all public Java methods (this dynamic functionality got introduced by javabridge years after I wrote pww).

However, you still need to wrap that native objecct so you can use in Python: `javabridge.get_collection_wrapper` should allow you to iterate the matrices. Then you can use `weka.core.typeconv.jdouble_matrix_to_ndarray` to turn an individual matrix into a numpy array.

All in all, tedious and probably not much quicker than your parsing...

**Comment by m-martin-j** [comment]
Hi,

then I am confused?! [0.2.10 on PyPI](https://pypi.org/project/python-weka-wrapper3/)

But subclassing needs to occur in Weka's Java code and cannot be done in Python, right?

Also, even if one went through all those matrix conversions, would this lead to an increase in numeric precision of the matrix-contained values?

**Comment by fracpete** [comment]
Apologies, my bad. I made a release from a different machine than I usually do (pww3 is a personal side project that I work on only now and then).

Yes, sub-classing has to happen on the Java side of things. pww3 is just a wrapper around Java code being executed in a JVM.

You might get a little bit more precision out of it, as you are using the internal double precision representation rather than the string notation:
https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#toString-double-

**Comment by m-martin-j** [comment]
Thank you for your input on this!

Closing this issue.

**Comment by fracpete** [comment]
Just committed some changes (https://github.com/fracpete/python-weka-wrapper3/commit/a8c86c99068ccf238d16f3acea09182280167223) that should help you.

The newly added methods `get_non_public_field` and `call_non_public_method` (module `weka.core.classes`) allow you to access/call private/protected Java fields/methods (NB: a Java security manager may prohibit this access, though).

The following example script shows how to use these methods and also how to access the `matricesDilca` field of the `weka.core.DilcaDistance` class and output the matrices as numpy arrays:
https://github.com/fracpete/python-weka-wrapper3-examples/blob/master/src/wekaexamples/core/non_public_access.py

You will need to install pww3 directly from source.

**Comment by m-martin-j** [comment]
Just as a brief checkback: Your approach fulfilled my case exactly. Thanks again.
