### ISSUE TITLE
Bayes net visualize tree

### ISSUE THREAD

**Issue by alvinkhoo91** [fracpete/python-weka-wrapper3#43]
![error](https://user-images.githubusercontent.com/65526263/192596846-069ec987-5d13-42b7-bd49-c2030143151f.png)

I tried visualizing Bayes net result but appeared error as above. J48 was fine following the example given.

**Comment by fracpete** [comment]
As you can see, BayesNet did not generate output in dot notation, but in [XML BIF](https://web.archive.org/web/20210122153549/http://sites.poli.usp.br/p/fabio.cozman/Research/InterchangeFormat/index.html). pww3 has no in-built functionality to visualize XML BIF.

**Comment by fracpete** [comment]
You might be able to use [pgmpy](https://pgmpy.org/readwrite/bif.html) for reading the BIF XML data and then visualize it, but I haven't tested that.

**Comment by fracpete** [comment]
Just pushed some experimental functionality for converting the XML BIF belief network structure into dot format, see example [BayesNet](https://github.com/fracpete/python-weka-wrapper3-examples/blob/master/src/wekaexamples/classifiers/bayesnet.py).
For this functionality to be available, you need to install pww3 directly from the [repo](https://fracpete.github.io/python-weka-wrapper3/install.html#github).

**Comment by alvinkhoo91** [comment]
![image](https://user-images.githubusercontent.com/65526263/192990140-e4ad749a-bbd0-4e10-9038-a927f31e0428.png)

Manually Install through python setup.py install, direct from git unable to install, having the error.

The graph seems doesn't work in my side, maybe I need reinstall library again ?

**Comment by fracpete** [comment]
Install `lxml` as well.
