### ISSUE TITLE
Plot multiple graphs

### ISSUE THREAD

**Issue by alvinkhoo91** [fracpete/python-weka-wrapper3#44]
How to display plot_roc and plot_classifier_errors at the same time?
I realize I have to close another window of matplot for the program to pop up another window for another program by using the weak. plot.classifiers

**Comment by fracpete** [comment]
Use `wait=False` as per documentation of the relevant methods, eg:

* https://fracpete.github.io/python-weka-wrapper3/weka.plot.html?highlight=plot_classifier#weka.plot.classifiers.plot_classifier_errors
* https://fracpete.github.io/python-weka-wrapper3/weka.plot.html?highlight=plot_roc#weka.plot.classifiers.plot_roc

Please use the mailing list for questions:

https://groups.google.com/g/python-weka-wrapper
