### ISSUE TITLE
How to use pyinstaller with weka?

### ISSUE THREAD

**Issue by hwy1992129** [fracpete/python-weka-wrapper3#45]
Hi, I need some help.
I am converting my python code to executable files with pyinstaller.
I encountered the error, as follows. I know nothing about java.... Packaged java environment not found?
![image](https://user-images.githubusercontent.com/70329303/204062880-65237357-cf6d-44ff-a453-a84d9bfa6b29.png)

**Comment by fracpete** [comment]
I don't think so that Java can be packaged with pyinstaller.
Did you install Java (eg [OpenJDK](https://adoptium.net/)) on the system that you were running your pyinstaller-generated installer?

**Comment by hwy1992129** [comment]
@fracpete I am using auto-py-to-exe, which is the GUI version of pyinstaller. I think I solved the problem by adding java into path. However, do you know any other methods to turn weka python into binary?

**Comment by fracpete** [comment]
I'm not a Windows user. Personally, I haven't come across a satisfactory way of turning Python into binaries.

For packaging large amounts of dependencies and libraries etc, I tend to use Docker under Linux. pww3 is published on Docker hub:

https://hub.docker.com/r/fracpete/pww3/tags

You can use one of these images as base image and then just add your own packages, scripts, etc. Here is some more information:

https://fracpete.github.io/python-weka-wrapper3/docker.html?highlight=docker

Of course, you will need WSL2 under Windows, if you want to use Docker.
