### ISSUE TITLE
sklweka JavaException: no/uib/cipr/matrix/Matrix

### ISSUE THREAD

**Issue by liboliba** [fracpete/python-weka-wrapper3#46]
Hello, 

I've got code and error below in Anaconda. My understanding was this was an old bug and resolved, but I still have this error. 
Any advise would be grateful.

Regards

import sklweka.jvm as jvm
from sklweka.dataset import load_arff, to_nominal_labels
from sklweka.classifiers import WekaEstimator
from sklweka.clusters import WekaCluster
from sklweka.preprocessing import WekaTransformer
from sklearn.model_selection import cross_val_score
from sklweka.datagenerators import DataGenerator, generate_data

# start JVM with Weka package support
jvm.start(packages=True)

# classification
X, y, meta = load_arff("contact-lenses.arff", class_index=2)
y = to_nominal_labels(y)
j48 = WekaEstimator(classname="weka.classifiers.trees.J48", options=["-M", "3"])
j48.fit(X, y)
scores = j48.predict(X)
probas = j48.predict_proba(X)
print("\nJ48 on iris\nactual label -> predicted label, probabilities")
for i in range(len(y)):
    print(y[i], "->", scores[i], probas[i])

# stop JVM
#jvm.stop()

---------------------------------------------------------------------------
JavaException                             Traceback (most recent call last)
Input In [2], in <cell line: 2>()
      1 # start JVM with Weka package support
----> 2 jvm.start(packages=True)
      4 # classification
      5 X, y, meta = load_arff("contact-lenses.arff", class_index=2)

File \\filestore.soton.ac.uk\users\ll1d19\.conda\envs\pww3\lib\site-packages\weka\core\jvm.py:156, in start(class_path, bundled, packages, system_cp, max_heap_size, system_info, auto_install, logging_level)
    153     env.add_variable("WEKA_HOME", weka_home)
    155 # initialize package manager
--> 156 javabridge.static_call(
    157     "Lweka/core/WekaPackageManager;", "loadPackages",
    158     "(Z)V",
    159     False)
    161 # output system info
    162 if system_info:

File \\filestore.soton.ac.uk\users\ll1d19\.conda\envs\pww3\lib\site-packages\javabridge\jutil.py:943, in static_call(class_name, method_name, sig, *args)
    941 ret_sig = sig[sig.find(')')+1:]
    942 nice_args = get_nice_args(args, args_sig)
--> 943 result = fn(*nice_args)
    944 return get_nice_result(result, ret_sig)

File \\filestore.soton.ac.uk\users\ll1d19\.conda\envs\pww3\lib\site-packages\javabridge\jutil.py:923, in make_static_call.<locals>.fn(*args)
    921 jexception = env.exception_occurred() 
    922 if jexception is not None:
--> 923     raise JavaException(jexception)
    924 return result

JavaException: no/uib/cipr/matrix/Matrix

**Comment by fracpete** [comment]
Can you please post the output of `pip freeze` in the environment that you are trying to run sklweka in?

**Comment by fracpete** [comment]
closed due to inactivity
