### ISSUE TITLE
Error installing Weka packages on Docker

### ISSUE THREAD

**Issue by raul-parada** [fracpete/python-weka-wrapper3#49]
Hi,

I've pulled and executed the docker CPU _0.2.14_cpu_. I'm trying to run a .py file where commands to install Weka packages are included. Inside the .py I have this header and install commands.

```
import os
import sys

sys.path
sys.path.append("/usr/lib/jvm/java-11-openjdk-amd64/bin/")
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64/"

import weka.core.jvm as jvm
from weka.core.converters import Loader
from weka.classifiers import Classifier
from weka.timeseries import WekaForecaster
from weka.core.dataset import Instances
from javabridge import JWrapper
import weka.core.packages as packages
from weka.filters import Filter

jvm.start(packages=True)
packages.install_package("timeseriesForecasting")
packages.install_package("alternatingModelTrees")

loader = Loader("weka.core.converters.ArffLoader")
```

However, I got the attached error.
[error.txt](https://github.com/fracpete/python-weka-wrapper3/files/12039693/error.txt)

**Comment by fracpete** [comment]
The important error messages are the following:
```
[DefaultPackageManager] trying http instead of https for https://weka.sourceforge.io/packageMetaData/repo.zip
[DefaultPackageManager] trying http instead of https for https://weka.sourceforge.io/packageMetaData/repo.zip
Unable to download repository zip archve (Three redirects were generated when trying to download https://weka.sourceforge.io/packageMetaData/repo.zip) - trying legacy routine...
[DefaultPackageManager] trying http instead of https for https://weka.sourceforge.io/packageMetaData/packageList.txt
[DefaultPackageManager] trying http instead of https for https://weka.sourceforge.io/packageMetaData/packageList.txt
java.io.IOException: Three redirects were generated when trying to download https://weka.sourceforge.io/packageMetaData/packageList.txt
```

This can happen when Sourceforge, which hosts the Weka packages, is temporarily down/inaccessible. I just tried it and it worked fine.

A few comments on your script:

1. The following statements are unnecessary, as only Java 8 is available from the Docker image/container:
```python
sys.path
sys.path.append("/usr/lib/jvm/java-11-openjdk-amd64/bin/")
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64/"
```

2. When installing packages in your script that won't make them available in your current JVM session. You need to restart your JVM session. If you stop/remove the Docker container, you will have to start from scratch again (any changes to a running Docker container will get discarded and everything is reinitialized from the Docker image blueprint). Instead, you should create your own Docker image with the relevant Weka packages included. Then you can start up a Docker container from that enhanced image, never worry about installing packages and just run your code with it. Have a look at the following section in the documentation:
https://fracpete.github.io/python-weka-wrapper3/docker.html#additional-weka-packages

**Comment by raul-parada** [comment]
Thanks. I still get the attached error. I did check and I have connection.
[error2.txt](https://github.com/fracpete/python-weka-wrapper3/files/12079679/error2.txt)

**Comment by fracpete** [comment]
There is no error in the above text file, only debugging output and warnings that can be disregarded.
If you are wondering why the script doesn't stop, you need to call `jvm.stop()` at the end.
