### ISSUE TITLE
Error while installing python-javabridge

### ISSUE THREAD

**Issue by jjeg1979** [fracpete/python-weka-wrapper3#51]
While doing pip install python-javabridge I get the following error:

ModuleNotFoundError: No module named 'numpy'

I have already install pip-23.3.2, numpy1-26-3 and added to the path python executable, (I am using python 3.12), and python scripts.

**Comment by fracpete** [comment]
What's the output of `pip freeze`?

**Comment by jjeg1979** [comment]
Hi, I already fixed it. Had mixed up Python version (3.11 and
numpy-3.11-mkl but python-javabridge only runs on python-310). Had to
install python 3.10 on a new vittual environment and got installed without
any issues.

Sorry!

Kindest Regards,

JJ
